name: directory
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2  # Add flutter_launcher_icons in dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/login_screen.jpeg
    - assets/bible.jpg
    - assets/church.jpeg
  
    - assets/profile.jpeg
  
    - assets/pithruvedi_logo.jpeg
    - assets/mathruvedi_logo.jpeg
    - assets/nurses_guild_logo.jpeg
    - assets/dsym_logo.jpeg
    - assets/little_flower.jpeg
  
    - assets/mother_mary.png
    - assets/st_george_small.png
    - assets/st_sebastian_smalll.png
    - assets/st_thomas_small.png
    - assets/holy_family_small.png
    - assets/infant_jesus_small.png
    - assets/little_flower_small.png
    - assets/st_joseph_small.png
    - assets/st_antony_small.png
    - assets/st_mary_large.png
    - assets/st_george_large.png
    - assets/infant_jesus_large.png
    - assets/st_thomas_large.png
    - assets/holy_family_large.png
    - assets/st_sebastian_large.png
    - assets/little_flower_large.png
    - assets/st_joseph_large.png
    - assets/st_antony_large.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon.png"  # Make sure this path points to your app icon
